use xplora_db;

INSERT INTO categoria (nombre) VALUES
    ('Aventuras y deportes'),
    ('Gastronomia'),
    ('Estadias'),
    ('Bienestar y relajación'),
    ('Cultura y entretenimiento'),
    ('Naturaleza y ecoturismo'),
    ('Experiencias urbanas'),
    ('Romanticismo y arte');


INSERT INTO rol (id_rol, nombre) VALUES
    (1, 'SuperAdministrador'),
    (2, 'Administrador'),
    (3, 'Usuario');

INSERT  INTO usuario (id_usuario, nombre, direccion, contrasena, telefono, id_rol, email) VALUES
    (1, 'Xplora Superadmin', 'Xplora Boulevard 123', '$2a$10$svyGvq1UnKdQNMNMc8/Nwep9WbyCJjNyDHvfs2wezPJgeC6TwPMcm', 12345678,1,'superadmin@xplora.com'),
    (2, 'Xplora Admin', 'Xplora Boulevard 123', '$2a$10$d8celupi88HCw5E07LAXeu9MBYKPDBpiNtgPxCvhstDN4CyXdSWxi', 12345678,2,'admin@xplora.com'),
    (3, 'Xplora Usuario', 'Xplora Boulevard 123', '$2a$10$bixazDGCVrXkoCtSkrzkle3uCyzUCHvkC3a0aYkZWxSBN5HBlbhLa', 12345678,3,'usuario@xplora.com');

INSERT INTO paquete_experiencia (id_paquete_experiencia, nombre, descripcion, precio, ubicacion, imagen, duracion, fecha_inicio, fecha_fin, id_categoria) VALUES
    (1, 'Spa de lujo', 'Regálate un momento de puro bienestar. Escápate del estrés y revitaliza tu cuerpo y mente con nuestra exclusiva experiencia: inicia tu viaje de relajación con una copa de espumante, seguida de un masaje de relajación profunda de 50 minutos para liberar tensiones, y sumérgete en un circuito de hidroterapia de 60 minutos con sauna seco y húmedo para eliminar toxinas, camas calientes para confortar tus músculos y jacuzzi para renovar tu energía, todo diseñado para brindarte una sensación de bienestar y relajación inigualable.', 150.00, 'Mendoza, Argentina', '/imagen_1.jpeg,/imagen_1.jpeg,/imagen_1.jpeg,/imagen_1.jpeg,/imagen_1.jpeg', '4 horas', @fecha_inicio := NOW() + INTERVAL FLOOR(RAND() * 7 + 1) DAY, @fecha_inicio + INTERVAL FLOOR(RAND() * 7 + 1) DAY, 1),
    (2, 'Paseo en kayak', 'Navega en kayak frente a uno de los glaciares más famosos. Embárcate en una aventura inolvidable con nuestro paseo en kayak, donde la serenidad del agua se fusiona con la emoción de la exploración. Deslízate suavemente por paisajes impresionantes, ya sea un tranquilo lago rodeado de montañas, un río serpenteante a través de exuberante vegetación o la costa marina con vistas espectaculares. Siente la libertad de remar a tu propio ritmo, descubriendo rincones ocultos y conectando con la naturaleza de una manera única. Nuestros guías expertos te acompañarán, asegurando una experiencia segura y enriquecedora, mientras compartes la belleza del entorno con amigos, familiares o en solitario.', 120.00, 'Buenos Aires, Argentina', '/imagen_2.jpeg,/imagen_3.jpeg,/imagen_4.jpeg,/imagen_5.jpeg,/imagen_6.jpeg', '3 horas', @fecha_inicio := NOW() + INTERVAL FLOOR(RAND() * 7 + 1) DAY, @fecha_inicio + INTERVAL FLOOR(RAND() * 7 + 1) DAY, 2),
    (3, 'Noche en cabaña', 'Escapada romántica en la montaña. Escápate a la serenidad de las montañas y sumérgete en una experiencia de tranquilidad inigualable en una acogedora cabaña. Despierta con el aroma de los pinos y el canto de los pájaros, mientras disfrutas de vistas panorámicas que te dejarán sin aliento. Relájate junto a la chimenea, saborea una taza de chocolate caliente y desconéctate del estrés cotidiano. Explora senderos naturales, respira aire puro y déjate envolver por la magia de la naturaleza. Ya sea que busques una escapada romántica, una aventura en solitario o un tiempo de calidad con amigos y familiares, nuestra cabaña en las montañas te brindará el refugio perfecto para recargar energías y crear recuerdos inolvidables.', 200.00, 'Bariloche, Argentina', '/imagen_8.jpeg', '1 noche', @fecha_inicio := NOW() + INTERVAL FLOOR(RAND() * 7 + 1) DAY, @fecha_inicio + INTERVAL FLOOR(RAND() * 7 + 1) DAY, 3),
    (4, 'Parapente en la montaña', 'Vuela sobre los Andes y disfruta de vistas panorámicas. Siente la adrenalina y la libertad de volar como un pájaro con nuestra experiencia de parapente en la montaña. Despega desde una cima impresionante y déjate llevar por las corrientes de aire, mientras contemplas paisajes espectaculares que se extienden a tus pies. Disfruta de la sensación única de planear en el cielo, sintiendo la brisa en tu rostro y la inmensidad de la naturaleza a tu alrededor. Nuestros instructores expertos te guiarán en cada paso, asegurando una experiencia segura y emocionante que te dejará recuerdos imborrables.', 150.00, 'Mendoza, Argentina', '/imagen_88.jpeg', '4 horas', @fecha_inicio := NOW() + INTERVAL FLOOR(RAND() * 7 + 1) DAY, @fecha_inicio + INTERVAL FLOOR(RAND() * 7 + 1) DAY, 1),
    (5, 'Tour de vinos premium', 'Cata exclusiva en viñedos históricos. Sumérgete en el mundo del vino con nuestro exclusivo tour en un viñedo premium, donde la elegancia y la pasión se fusionan en una experiencia inolvidable. Recorre viñedos centenarios, descubre los secretos de la elaboración del vino y degusta una selección de nuestras mejores cosechas, guiado por expertos enólogos que compartirán contigo su conocimiento y pasión. Disfruta de un ambiente sofisticado y relajado, mientras admiras paisajes espectaculares y te deleitas con maridajes exquisitos que realzarán los sabores de cada vino. Una experiencia sensorial única para los amantes del buen vino y la naturaleza.', 120.00, 'Buenos Aires, Argentina', '/imagen_9.jpeg', '3 horas', @fecha_inicio := NOW() + INTERVAL FLOOR(RAND() * 7 + 1) DAY, @fecha_inicio + INTERVAL FLOOR(RAND() * 7 + 1) DAY, 2),
    (6, 'Aventura en glamping', 'Noche de lujo en una tienda bajo las estrellas. Sumérgete en la naturaleza sin renunciar al confort con nuestra experiencia de glamping, una fusión perfecta entre aventura y lujo. Duerme bajo un manto de estrellas en una tienda elegantemente equipada, con comodidades de hotel y detalles cuidadosamente seleccionados. Despierta con el canto de los pájaros y disfruta de desayunos gourmet al aire libre, rodeado de paisajes impresionantes. Explora senderos naturales, relájate en jacuzzis privados y disfruta de fogatas bajo la luna. El glamping te ofrece la oportunidad de conectar con la naturaleza de una manera única y memorable, creando recuerdos inolvidables en un entorno mágico y exclusivo.', 200.00, 'Bariloche, Argentina', '/imagen_10.jpeg', '1 noche', @fecha_inicio := NOW() + INTERVAL FLOOR(RAND() * 7 + 1) DAY, @fecha_inicio + INTERVAL FLOOR(RAND() * 7 + 1) DAY, 3),
    (7, 'Rafting en aguas blancas', 'Descenso extremo por rápidos clase III y IV. Siente la descarga de adrenalina con nuestra experiencia de rafting en aguas blancas, donde la aventura y la naturaleza se fusionan en un emocionante descenso. Navega por rápidos desafiantes, siente la fuerza del agua y admira paisajes impresionantes desde una perspectiva única. Nuestros guías expertos te acompañarán en cada paso, asegurando tu seguridad y compartiendo su conocimiento sobre el río y su entorno. Ya sea que busques una experiencia llena de emoción con amigos o una aventura en solitario, el rafting en aguas blancas te brindará recuerdos inolvidables y la sensación de haber conquistado la naturaleza en su estado más salvaje.', 150.00, 'Mendoza, Argentina', '/imagen_11.jpeg', '4 horas', @fecha_inicio := NOW() + INTERVAL FLOOR(RAND() * 7 + 1) DAY, @fecha_inicio + INTERVAL FLOOR(RAND() * 7 + 1) DAY, 1),
    (8, 'Experiencia gastronómica fusión', 'Menú degustación con maridaje en restaurante de autor. Embárcate en un viaje culinario sin fronteras con nuestra experiencia gastronómica fusión, donde los sabores del mundo se entrelazan para crear combinaciones sorprendentes y deliciosas. Descubre platos innovadores que fusionan técnicas y ingredientes de diferentes culturas, desde la sutileza de la cocina asiática hasta la intensidad de los sabores latinos, pasando por la elegancia de la gastronomía mediterránea. Nuestros chefs expertos te guiarán a través de un menú degustación cuidadosamente elaborado, donde cada bocado es una explosión de sabor y una invitación a explorar nuevos horizontes culinarios. Disfruta de un ambiente sofisticado y relajado, donde la creatividad y la pasión por la gastronomía se unen para ofrecerte una experiencia única e inolvidable.', 120.00, 'Buenos Aires, Argentina', '/imagen_12.jpeg', '3 horas', @fecha_inicio := NOW() + INTERVAL FLOOR(RAND() * 7 + 1) DAY, @fecha_inicio + INTERVAL FLOOR(RAND() * 7 + 1) DAY, 2),
    (9, 'Refugio alpino exclusivo', 'Hospedaje en cabaña con chimenea y vistas al lago. Escápate a la cumbre de la exclusividad con nuestra experiencia en un refugio alpino de lujo, donde la elegancia se encuentra con la majestuosidad de la montaña. Disfruta de vistas panorámicas impresionantes desde la calidez de un refugio diseñado con detalles exquisitos, donde el confort y la sofisticación se fusionan en perfecta armonía. Saborea la alta gastronomía local, relájate en spas de montaña y explora paisajes nevados con actividades exclusivas. Ya sea que busques una escapada romántica, una aventura en solitario o un retiro con amigos, nuestro refugio alpino te brindará una experiencia inolvidable, donde cada detalle está cuidadosamente pensado para superar tus expectativas.', 200.00, 'Bariloche, Argentina', '/imagen_13.jpeg', '1 noche', @fecha_inicio := NOW() + INTERVAL FLOOR(RAND() * 7 + 1) DAY, @fecha_inicio + INTERVAL FLOOR(RAND() * 7 + 1) DAY, 3),
    (10, 'Buceo en aguas cristalinas', 'Explora arrecifes y vida marina en un entorno único. Sumérgete en un mundo submarino de ensueño con nuestra experiencia de buceo en aguas cristalinas, donde la belleza y la tranquilidad se fusionan en una aventura inolvidable. Explora arrecifes de coral vibrantes, descubre la diversidad de la vida marina y siente la emoción de flotar en un entorno mágico y silencioso. Nuestros instructores expertos te guiarán en cada paso, asegurando tu seguridad y compartiendo su conocimiento sobre el ecosistema marino. Ya sea que seas un buceador experimentado o un principiante, esta experiencia te brindará la oportunidad de conectar con la naturaleza de una manera única y crear recuerdos que durarán toda la vida.', 150.00, 'Mendoza, Argentina', '/imagen_14.jpeg', '4 horas', @fecha_inicio := NOW() + INTERVAL FLOOR(RAND() * 7 + 1) DAY, @fecha_inicio + INTERVAL FLOOR(RAND() * 7 + 1) DAY, 1),
    (11, 'Taller de cocina internacional', 'Aprende técnicas de chefs expertos en un entorno exclusivo. Sumérgete en un viaje culinario global con nuestro taller de cocina internacional, donde aprenderás a preparar platos auténticos de diferentes culturas, guiado por chefs expertos que compartirán sus secretos y técnicas. Descubre la riqueza de sabores y aromas de la cocina tailandesa, italiana, mexicana o cualquier otra cultura que elijas explorar. Participa en una experiencia práctica y divertida, donde cocinarás junto a otros apasionados de la gastronomía, degustarás tus creaciones y te llevarás a casa recetas y conocimientos para sorprender a tus amigos y familiares.', 120.00, 'Buenos Aires, Argentina', '/imagen_15.jpeg', '3 horas', @fecha_inicio := NOW() + INTERVAL FLOOR(RAND() * 7 + 1) DAY, @fecha_inicio + INTERVAL FLOOR(RAND() * 7 + 1) DAY, 2),
    (12, 'Campamento en la nieve', 'Vive la aventura de dormir en la montaña nevada. Atrévete a vivir una aventura invernal inolvidable con nuestra experiencia de campamento en la nieve, donde la magia del paisaje nevado se combina con la emoción de la vida al aire libre. Sumérgete en un mundo de tranquilidad y belleza, rodeado de montañas cubiertas de nieve y cielos estrellados. Construye tu propio refugio, aprende técnicas de supervivencia en la nieve y disfruta de actividades emocionantes como caminatas con raquetas de nieve y construcción de iglús. Comparte historias alrededor de una fogata, degusta comidas calientes bajo la luna y duerme en tiendas de campaña diseñadas para resistir las bajas temperaturas. Una experiencia única para conectar con la naturaleza en su estado más puro y crear recuerdos imborrables.', 200.00, 'Bariloche, Argentina', '/imagen_16.jpeg', '1 noche', @fecha_inicio := NOW() + INTERVAL FLOOR(RAND() * 7 + 1) DAY, @fecha_inicio + INTERVAL FLOOR(RAND() * 7 + 1) DAY, 3);


INSERT INTO pedido (estado, es_regalo, total, id_paquete_experiencia) VALUES
    ('Confirmado', FALSE, 150.00, 1),
    ('Pendiente', TRUE, 120.00, 2),
    ('Completado', FALSE, 200.00, 3);

-- INSERT INTO metodo_pago (nombre) VALUES
--     ('Tarjeta de crédito'),
--     ('PayPal'),
--     ('Transferencia bancaria');

-- INSERT INTO pago (monto, estado, id_pedido, id_metodo_pago) VALUES
--     (150.00, 'Aprobado', 1, 1),
--     (120.00, 'Pendiente', 2, 2),
--     (200.00, 'Aprobado', 3, 3);
INSERT INTO categoria (nombre) VALUES