# Local development database
spring.datasource.url=jdbc:mysql://localhost:3306/xplora_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=app_user
spring.datasource.password=root

# Mail properties: 
spring.mail.host=localhost
spring.mail.port=2525
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# Url base de la app:
app.url=http://localhost:8080